#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# nitrogen --restore
# picom --no-fading-openclose &
picom &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III

bspc config top_padding			 48
bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# kde specific config
# krunner
bspc rule -a krunner state=floating
# rofi
bspc rule -a Rofi state=floating
# # klipper - The following rule is NOT WORKING!
# bspc rule -a plasmashell:*:klipper state=floating rectangle='592x592+3048+56'
# plasmashell
bspc rule -a plasmashell state=floating sticky=on border=off
# sublime text
bspc rule -a Sublime_text state=floating
# dolphin
bspc rule -a dolphin state=floating
# system settings
bspc rule -a systemsettings state=floating
