#! /bin/sh

# wallpaper
nitrogen --restore
# compositor
picom &
# hotkeys
pgrep -x sxhkd > /dev/null || sxhkd &
# polybar
$HOME/.config/polybar/launch.sh


# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III

bspc config top_padding			 48
bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Always open chromium in desktop #2
bspc rule -a Chromium desktop='^2'


# general bspwm rules
#
# rofi
bspc rule -a Rofi state=floating
# sublime text
bspc rule -a Sublime_text state=floating


# kde specific bspwm rules
#
# krunner
bspc rule -a krunner state=floating
# plasmashell
bspc rule -a plasmashell state=floating sticky=on border=off
# dolphin
bspc rule -a dolphin state=floating
# system settings
bspc rule -a systemsettings state=floating


# open any application in a receptacle, if one available
# shifted to .local/bin/rxrofi script
#   rofi -show combi -normal-window
#   bspc rule -a *:* -o node=any.leaf.!window.local
